# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d0cafc1980fb771dbc2552887b89bffd2c98bcbf64a9fc80d82f790c258ee7ed8c79118889bd6d0be12d8074f9d008dacf486e2e47b8bb419e82285463b8f47

test:
  secret_key_base: 79fbc207e4b5a40c9cfa93a159b00a1eaaeee6e46e8e60ff5f8ccf12505169aad281f90982fdc1adb5fc689e67219e4477845e04a87e2669d6d6058bdf6e24f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
